version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tutorial_backend
    restart: always
    ports:
      - "5005:5000"
    environment:
      - PORT=5000
      - DB_HOST=db.iwldbospzwkdltezahml.supabase.co
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Patochukwu1
      - JWT_SECRET=super_secret_jwt_key_123!
      - RESEND_API_KEY=re_RUmwx1Uq_Fj8skSyvA7pnMPvEqtsWyD6U
      - MAIL_FROM=Creators Tutorial Arena <onboarding@resend.dev>
      - FRONTEND_URL=http://localhost:5175

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tutorial_frontend
    ports:
      - "5175:5173"
    environment:
      - VITE_API_URL=http://localhost:5005/api
    depends_on:
      - backend
